#!/bin/bash

# This script deploys JDK, Gradle
# Run as below
# ./deploy-jdk-gradle gradle-4.10.2-bin.zip
# Author: Eren Seymen (eren.seymen@orioninc.com)

# Add LINEs if not exist to /etc/profile file
FILE_NAME="/etc/profile"
LINE='JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64'
grep -qxF "$LINE" $FILE_NAME || echo "$LINE" >> $FILE_NAME
LINE='PATH=$PATH:$JAVA_HOME/bin'
grep -qxF "$LINE" $FILE_NAME || echo "$LINE" >> $FILE_NAME
LINE='export JAVA_HOME'
grep -qxF "$LINE" $FILE_NAME || echo "$LINE" >> $FILE_NAME
LINE='GRADLE_HOME=/opt/gradle/gradle_latest'
grep -qxF "$LINE" $FILE_NAME || echo "$LINE" >> $FILE_NAME
LINE='PATH=$PATH:$GRADLE_HOME/bin'
grep -qxF "$LINE" $FILE_NAME || echo "$LINE" >> $FILE_NAME
LINE='export GRADLE_HOME'
grep -qxF "$LINE" $FILE_NAME || echo "$LINE" >> $FILE_NAME
LINE='export PATH'
grep -qxF "$LINE" $FILE_NAME || echo "$LINE" >> $FILE_NAME
. /etc/profile


echo "Gradle deploying..."
echo BEFORE
gradle -v > /tmp/gradle-version-output 2>&1
grep "Gradle " /tmp/gradle-version-output

mkdir -p /opt/gradle
rm -rf /opt/gradle/gradle*
unzip -d /opt/gradle "$1" > /dev/null 2>&1
chown -R root:root /opt/gradle/gradle*
mv /opt/gradle/gradle* /opt/gradle/gradle_latest

echo AFTER
gradle -v > /tmp/gradle-version-output 2>&1
grep "Gradle " /tmp/gradle-version-output

